---
- name: Emerge Gentoo Sources
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge gentoo-sources;'
  args:
    creates: /mnt/gentoo/usr/src/linux/arch
  tags:
    - kernel

- name: Copy kernel config
  copy:
    src: kernels/{{ kernel }}
    dest: /mnt/gentoo/usr/src/linux/.config
  tags:
    - kernel

- name: Configure kernel
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile;cd /usr/src/linux;make oldconfig'
  tags:
    - kernel

- name: Compile kernel
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make {{ make_opts }}'
  tags:
    - kernel

- name: Install kernel & modules
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make modules_install; make install'
  tags:
    - kernel
