---
# tasks file for ansible-gentoo
- name: Deploy User's Authorized Key to Root
  authorized_key: user=root key="{{ lookup('file', pubkey) }}"

- include: storage.yml
- stat:
    path: /tmp/base_completed
  register: base_completed

- include_tasks: base.yml
  when: base_completed.stat.exists == False


- include: kernel.yml
- include: networking.yml
- include: system.yml
- include: packages.yml
- include: reboot.yml
