---
- import_tasks: storage.yml

- stat:
    path: /tmp/base_completed
  register: base_completed

- import_tasks: base.yml
  when: base_completed.stat.exists == False

- import_tasks: kernel.yml

- import_tasks: networking.yml

- import_tasks: system.yml

- import_tasks: packages.yml

- import_tasks: reboot.yml
