---
- name: Install Miscellaneous Packages
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge -u {{ item.name }}'
  with_items:
    - name: app-editors/vim
    - name: app-misc/tmux
    - name: app-shells/zsh
    - name: dev-lang/python
    - name: dev-vcs/git
    - name: net-misc/dhcpcd
    - name: net-misc/netifrc
    - name: sys-fs/xfsprogs